language: php

php:
    - '7.0'
    - '7.1'

install:
    - composer install

before_script:
    - mkdir -p build/logs

script:
    - php vendor/bin/phpcs
    - php vendor/bin/phpmd src/,tests/ text cleancode,codesize,controversial,design,naming,unusedcode
    - php vendor/bin/phpcpd src/ tests/
    - php vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v
